
export {default as Apple } from './images/apple.svg'
export {default as Email } from './images/email.svg'
export {default as Google } from './images/google.svg'
export {default as Name } from './images/name.svg'
export {default as Password } from './images/password.svg'
export {default as Logo } from './logo/logo.svg'
export {default as ShowEye } from './images/eye.svg'

export {default as User } from './images/user.svg'
export {default as Menu } from './images/menu.svg'
export {default as Invoice } from './images/invoice.svg'
export {default as Notification } from './images/notification.svg'
export {default as SearchIcon } from './images/search.svg'
export {default as Options } from './images/options.svg'